---

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

services:
  - mongodb

branches:
  only:
    - master
    - develop

before_script:
  - mkdir -p build/coverage

script:
 - ./.travis/run.sh

after_script:
 - php vendor/bin/coveralls

notifications:
  email: false

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.4
    - php: 7
    - php: hhvm