sudo: false
language: php
matrix:
  fast_finish: true
  include:
  - php: 5.5
  - php: 5.6
  - php: 7
  - php: hhvm
  allow_failures:
  - php: 7
  - php: hhvm
services:
- mongodb
cache:
  directories:
  - $HOME/.composer/cache
script:
- composer self-update
- composer config --global github-oauth.github.com ${GH_TOKEN}
- ./.travis/run.sh
after_script:
- php vendor/bin/coveralls
notifications:
  irc: irc.freenode.org#matryoshka.dev
  email: false
env:
  global:
    secure: fuadEg/WNfG73dvJMqpIEnipEOGKDRFEWddw40sWxB8bVzVslmaEbufTdP1VJzNWmNg3lyVPr+xNOggWtWEmYImiFZcN1gNJ/0CDgAjSqBUT40LLWgySqfb36HM/Ve6Epkd0ySsg/h5rn/x8irr6i+EYSU3WyDsKsZzyJjeIRxY=