---

language: php

php:
  - 5.6
  - 5.5
  - 5.4

services:
  - mongodb

branches:
  only:
    - master
    - develop

script:
 - ./.travis/run.sh

notifications:
  irc: "irc.freenode.org#matryoshka.dev"
  email: false