---

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

services:
  - mongodb

branches:
  only:
    - master
    - develop

before_script:
  - mkdir -p build/coverage

script:
 - ./.travis/run.sh

after_script:
 - php vendor/bin/coveralls

notifications:
  irc: "irc.freenode.org#matryoshka.dev"
  email: false


matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm