---

before_script:
  - ./.travis/prepare.sh

language: php

php:
  - 5.6
  - 5.5
  - 5.4

services:
  - mongodb

branches:
  only:
    - master
    - develop

install:
  - composer self-update
  - composer install --dev --prefer-source

script:
 - vendor/bin/phpunit